### ISSUE TITLE
Roadmap!

### ISSUE THREAD

**Issue by Deadpikle** [NetSparkleUpdater/NetSparkle#61]
**Current item being worked on: finishing up! Creating update guide (half done), deprecating old NuGet for `NetSparkle.New`, etc. Almost there!**

Hi everyone,

This repo has been around for quite some time, and I've never gotten around to making a 2.0 version of NetSparkle.

Here are my goals starting in August 2019 (not given in order):

### Complete

- [x] Go through the code and clean it up
- [x] Make names of fields, events, etc. consistent
- [x] Finish any refactoring work
- [x] Totally, 100% separate the UI from the update logic. Have two separate UI DLLs: one for WinForms and one for WPF. The UI Factory can always be utilized for your own UI.
- [x] Create a NetSparkle organization and move this repo there for easier discoverability (See #73 -- name chosen; just need to create it and move repo)
- [x] Push an update to the original repo [here](https://github.com/dei79/netsparkle) that points people to the new organization (Waiting on above bullet point)
- [x] Start pushing 2.0 alpha/beta builds to the [NetSparkle NuGet repo](https://www.nuget.org/packages/NetSparkle/) for testing and better Google-ing (See #84 -- about 50-75% done)
- [x] Other enhancements to NetSparkle
    - [x] Allow for custom object that will download app cast
    - [x] Allow for custom object that will download update file(s)
    - [x] Allow for custom object that handles app cast downloading and parsing
- [x] Update [this SO post](https://stackoverflow.com/questions/8559887/netsparkle-vs-sparkledotnet) via a comment so that people can see from there that new things are happening
- [x] Test (and fix if necessary) `SecurityMode.UseIfPossible` based on the report in #89 -- may not work when a signature isn't available
- [x] Create update guide from whatever version is there to this version (can probably just crawl through repo histories / fork history to do this)  [WIP already, see README.md]
- [x] Make sure documentation for this project is good enough for new users who will be investigating things from NuGet (Update: Good enough for now. We've got docs up on the website now as well as XML docs most everywhere, plus gitter and other things here in README.md)
- [x] Create new logo/icon (tracking this in #100)  
- [x] Update README.md appropriately (badge for NuGet repo, etc.)
- [x] Bump this version up to "2.0" so that it looks like an upgrade from random folks who don't know the fork of a fork of a fork history of NetSparkle, especially since it probably breaks compatibility
- [x] Deprecate `NetSparkle.New.Tools` in lieu of `NetSparkleUpdater.Tools` and remove from search results

### Not complete

- [x] Decide if core package will be ~~`NetSparkleUpdater.Core`~~ or `NetSparkleUpdater.SparkleUpdater`.
- [x] Create NetSparkleUpdater.SparkleUpdater feed and update all refs in projects, etc. to point to that package (tools & WinForms .NET Framework nuspec updating too)
- [x] Deprecate [NetSparkle nuget feed](https://www.nuget.org/packages/NetSparkle/) and point people to NetSparkleUpdater.NetSparkle (I did not originally create this feed but have been given rights to write to it)
- [x] Deprecate [NetSparkle.New nuget feed](https://www.nuget.org/packages/NetSparkle.New/) and point people to NetSparkleUpdater.SparkleUpdater -- add new version with just a readme.txt pointing people to the new repo/nuget or something
- [ ] Consider manually adding a new version with a readme to point people to the new version along with deprecation (see [tutorial here](https://weblog.west-wind.com/posts/2018/Jan/29/Distributing-Content-and-Showing-a-ReadMe-file-in-a-NET-Core-Nuget-Package))
- [x] Unlist old NetSparkle packages under our control to remove confusion
- [x] Update repo releases page with info on v2.0 and binaries to download (can manually grab these from NuGet for now)
- [x] Update Microsoft docs and the WinSparkle issue I filed to point to `NetSparkleUpdater`

**Comment by Deadpikle** [comment]
Clearly I didn't start this in August. But I am starting today in October! So I'm not dead -- if there are any urgent issues, please let me know so that I can get them fixed more quickly for your use case.

**Comment by Deadpikle** [comment]
To track progress, check out the 2.0.0 milestone and/or watch issues and/or watch recent commits to see what I'm working on. Soon™️!

**Comment by cjmurph** [comment]
Hi, I just want to throw this idea out there regarding the separation of the user interface from the core netsparkle project.

Can I suggest that netsparkle just throws events and doesn't open dialogs at all, that it doesn't need a uifactory? 

The GUI specific projects for wpf and winforms could reference netsparkle, wrap sparkle to make sparklewpf and sparkleforms that do pop dialogs and have the uifactory etc, but that are in fact just responding to events from an internal sparkle instance.

I can make a branch and quickly mock something up to explain better if it doesn't make sense.

**Comment by Deadpikle** [comment]
@cjmurph Hi!

It's an idea. I think I understand what you mean -- keep the core event handling and updates in NetSparkle.dll and _all_ UI handling elsewhere.

I think the biggest problem I see with it right now is the repeated logic between the two UIs. It also becomes much more labor intensive to create your own UI (something I want to keep easy), as it means a lot more work/copied code. There might be a clever way to avoid that...but the layering necessary to do so (another UI project/dll that the UIs derive from?) probably isn't worth the effort/obscurity in terms of code.

Open to arguments/ideas otherwise! :)

**Comment by cjmurph** [comment]
I've made a rough go at it here [https://github.com/cjmurph/NetSparkle/tree/seperate-ui](url)
there's definitely a cleaner way to do it to reduce maintenance, but you'll get the idea.
It builds and the test apps work.

**Comment by Deadpikle** [comment]
@cjmurph Not wanting to ignore what you've done. I've got a busy week this week. If you want your other PR merged for work/software reasons, let me know. Otherwise it'll sit tight for a few days. Thanks. :)

**Comment by cjmurph** [comment]
No rush, just trying to help and give some different ideas. If it's not the direction you want to go, that's cool too :)

**Comment by Deadpikle** [comment]
Moving this discussion on further refactoring to #77. Thanks, and sorry for the wait.

**Comment by flemingm** [comment]
Great Work!

**Comment by Deadpikle** [comment]
2.0 is now finally, finally, finally, finally, finally released. Ooof, that took a while.

🥳
